-- =========================================================
-- CATEGORY
-- =========================================================

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- BRAND
-- =========================================================

CREATE TABLE brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- PRODUCTS
-- Produit principal : T-shirt Nike, Jean Levi's, etc.
-- =========================================================

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR(255) NOT NULL,
    description TEXT,

    category_id BIGINT NOT NULL,
    brand_id BIGINT,

    purchase_price NUMERIC(15,2) NOT NULL DEFAULT 0,
    selling_price NUMERIC(15,2) NOT NULL,

    active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_product_category
        FOREIGN KEY (category_id)
        REFERENCES categories(id),

    CONSTRAINT fk_product_brand
        FOREIGN KEY (brand_id)
        REFERENCES brands(id),

    CONSTRAINT chk_product_purchase_price
        CHECK (purchase_price >= 0),

    CONSTRAINT chk_product_selling_price
        CHECK (selling_price >= 0)
);


-- =========================================================
-- PRODUCT VARIANTS
-- Chaque taille/couleur possède son propre code-barres
-- =========================================================

CREATE TABLE product_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    product_id BIGINT NOT NULL,

    sku VARCHAR(100) NOT NULL UNIQUE,
    barcode VARCHAR(100) NOT NULL UNIQUE,

    size VARCHAR(30),
    color VARCHAR(100),

    quantity INTEGER NOT NULL DEFAULT 0,
    minimum_stock INTEGER NOT NULL DEFAULT 5,

    active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_variant_product
        FOREIGN KEY (product_id)
        REFERENCES products(id),

    CONSTRAINT chk_variant_quantity
        CHECK (quantity >= 0),

    CONSTRAINT chk_variant_minimum_stock
        CHECK (minimum_stock >= 0)
);


-- =========================================================
-- USERS
-- =========================================================

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,

    first_name VARCHAR(100),
    last_name VARCHAR(100),

    role VARCHAR(50) NOT NULL DEFAULT 'CASHIER',

    active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- CUSTOMERS
-- =========================================================

CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    email VARCHAR(255),

    loyalty_points INTEGER NOT NULL DEFAULT 0,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- SALES
-- Une ligne = une transaction POS
-- =========================================================

CREATE TABLE sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    sale_number VARCHAR(50) NOT NULL UNIQUE,

    customer_id BIGINT,
    cashier_id BIGINT NOT NULL,

    subtotal NUMERIC(15,2) NOT NULL DEFAULT 0,
    discount NUMERIC(15,2) NOT NULL DEFAULT 0,
    total NUMERIC(15,2) NOT NULL,

    amount_received NUMERIC(15,2),
    change_amount NUMERIC(15,2) DEFAULT 0,

    status VARCHAR(30) NOT NULL DEFAULT 'COMPLETED',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_sale_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers(id),

    CONSTRAINT fk_sale_cashier
        FOREIGN KEY (cashier_id)
        REFERENCES users(id),

    CONSTRAINT chk_sale_total
        CHECK (total >= 0),

    CONSTRAINT chk_sale_discount
        CHECK (discount >= 0)
);


-- =========================================================
-- SALE ITEMS
-- Détail des produits vendus
-- =========================================================

CREATE TABLE sale_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    sale_id BIGINT NOT NULL,
    product_variant_id BIGINT NOT NULL,

    quantity INTEGER NOT NULL,

    unit_price NUMERIC(15,2) NOT NULL,

    discount NUMERIC(15,2) NOT NULL DEFAULT 0,

    subtotal NUMERIC(15,2) NOT NULL,

    CONSTRAINT fk_sale_item_sale
        FOREIGN KEY (sale_id)
        REFERENCES sales(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_sale_item_variant
        FOREIGN KEY (product_variant_id)
        REFERENCES product_variants(id),

    CONSTRAINT chk_sale_item_quantity
        CHECK (quantity > 0),

    CONSTRAINT chk_sale_item_price
        CHECK (unit_price >= 0)
);


-- =========================================================
-- PAYMENTS
-- Permet paiement espèces, carte, MVola, etc.
-- Et paiement mixte
-- =========================================================

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    sale_id BIGINT NOT NULL,

    payment_method VARCHAR(50) NOT NULL,

    amount NUMERIC(15,2) NOT NULL,

    transaction_reference VARCHAR(255),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_payment_sale
        FOREIGN KEY (sale_id)
        REFERENCES sales(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_payment_amount
        CHECK (amount > 0)
);


-- =========================================================
-- STOCK MOVEMENTS
-- Historique complet de chaque modification du stock
-- =========================================================

CREATE TABLE stock_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    product_variant_id BIGINT NOT NULL,

    movement_type VARCHAR(50) NOT NULL,

    quantity INTEGER NOT NULL,

    stock_before INTEGER,
    stock_after INTEGER,

    reference VARCHAR(100),
    description VARCHAR(500),

    created_by BIGINT,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_stock_movement_variant
        FOREIGN KEY (product_variant_id)
        REFERENCES product_variants(id),

    CONSTRAINT fk_stock_movement_user
        FOREIGN KEY (created_by)
        REFERENCES users(id),

    CONSTRAINT chk_stock_movement_quantity
        CHECK (quantity <> 0)
);


-- =========================================================
-- SUPPLIERS
-- =========================================================

CREATE TABLE suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR(255) NOT NULL,

    phone VARCHAR(50),
    email VARCHAR(255),
    address TEXT,

    active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- PURCHASE ORDERS
-- Commandes fournisseurs
-- =========================================================

CREATE TABLE purchase_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_number VARCHAR(50) NOT NULL UNIQUE,

    supplier_id BIGINT NOT NULL,

    status VARCHAR(50) NOT NULL DEFAULT 'DRAFT',

    total NUMERIC(15,2) NOT NULL DEFAULT 0,

    created_by BIGINT,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    received_at TIMESTAMP,

    CONSTRAINT fk_purchase_supplier
        FOREIGN KEY (supplier_id)
        REFERENCES suppliers(id),

    CONSTRAINT fk_purchase_user
        FOREIGN KEY (created_by)
        REFERENCES users(id)
);


-- =========================================================
-- PURCHASE ITEMS
-- =========================================================

CREATE TABLE purchase_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    purchase_order_id BIGINT NOT NULL,

    product_variant_id BIGINT NOT NULL,

    quantity_ordered INTEGER NOT NULL,

    quantity_received INTEGER NOT NULL DEFAULT 0,

    purchase_price NUMERIC(15,2) NOT NULL,

    CONSTRAINT fk_purchase_item_order
        FOREIGN KEY (purchase_order_id)
        REFERENCES purchase_orders(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_purchase_item_variant
        FOREIGN KEY (product_variant_id)
        REFERENCES product_variants(id),

    CONSTRAINT chk_quantity_ordered
        CHECK (quantity_ordered > 0),

    CONSTRAINT chk_quantity_received
        CHECK (quantity_received >= 0)
);


-- =========================================================
-- INVENTORIES
-- Session d'inventaire physique
-- =========================================================

CREATE TABLE inventories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    inventory_number VARCHAR(50) NOT NULL UNIQUE,

    status VARCHAR(30) NOT NULL DEFAULT 'IN_PROGRESS',

    created_by BIGINT,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    validated_at TIMESTAMP,

    CONSTRAINT fk_inventory_user
        FOREIGN KEY (created_by)
        REFERENCES users(id)
);


-- =========================================================
-- INVENTORY ITEMS
-- =========================================================

CREATE TABLE inventory_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    inventory_id BIGINT NOT NULL,

    product_variant_id BIGINT NOT NULL,

    expected_quantity INTEGER NOT NULL,

    counted_quantity INTEGER NOT NULL DEFAULT 0,

    difference INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT fk_inventory_item_inventory
        FOREIGN KEY (inventory_id)
        REFERENCES inventories(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_inventory_item_variant
        FOREIGN KEY (product_variant_id)
        REFERENCES product_variants(id),

    CONSTRAINT uq_inventory_variant
        UNIQUE (inventory_id, product_variant_id)
);


TRUNCATE TABLE
    inventory_items,
    inventory,
    purchase_items,
    purchase_orders,
    stock_movements,
    payments,
    sale_items,
    sales,
    customers,
    product_variant,
    products,
    brand,
    categories,
    suppliers,
    users
RESTART IDENTITY CASCADE;